# Generated by Django 3.1.7 on 2021-03-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210326_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='dudate',
            new_name='duedate',
        ),
    ]
